### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by medo600** [RoySegall/facebook-messenger-send-api#2]
I downloaded the files and run terminal in files's folder 
composer update
and download it's dependencies and i change access token and recipient in testing.php 
but give me in browser console "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" 
I want  solution pls

**Comment by RoySegall** [comment]
If that's a 500 error - can you give me the logs?

**Comment by medo600** [comment]
Tihs is my log 👍 

[04-Aug-2018 13:00:39 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=EAAWZA5YNHROMBACZBbgEsZBEKADq1B9OhypiOAIpMokcnIKL8F3K0SYUenzTkVVLGPWLGQpGynUB3aeHZAoWzGCx2XJmqhzOFl7zCa577QSy51oKPYWWzLeC8lNoeqEaLpjNFArcZCEQZCrUBsKxlCZC8hZCj4Wfw2fSp2aZBlUQ7AACAerP273AHBIFszPgzuWQZD` resulted in a `400 Bad Request` response:
{"error":{"message":"Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi (truncated...)
 in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[04-Aug-2018 13:00:42 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=EAAWZA5YNHROMBACZBbgEsZBEKADq1B9OhypiOAIpMokcnIKL8F3K0SYUenzTkVVLGPWLGQpGynUB3aeHZAoWzGCx2XJmqhzOFl7zCa577QSy51oKPYWWzLeC8lNoeqEaLpjNFArcZCEQZCrUBsKxlCZC8hZCj4Wfw2fSp2aZBlUQ7AACAerP273AHBIFszPgzuWQZD` resulted in a `400 Bad Request` response:
{"error":{"message":"Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi (truncated...)
 in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[04-Aug-2018 13:00:50 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=EAAWZA5YNHROMBACZBbgEsZBEKADq1B9OhypiOAIpMokcnIKL8F3K0SYUenzTkVVLGPWLGQpGynUB3aeHZAoWzGCx2XJmqhzOFl7zCa577QSy51oKPYWWzLeC8lNoeqEaLpjNFArcZCEQZCrUBsKxlCZC8hZCj4Wfw2fSp2aZBlUQ7AACAerP273AHBIFszPgzuWQZD` resulted in a `400 Bad Request` response:
{"error":{"message":"Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi (truncated...)
 in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[04-Aug-2018 13:00:52 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=EAAWZA5YNHROMBACZBbgEsZBEKADq1B9OhypiOAIpMokcnIKL8F3K0SYUenzTkVVLGPWLGQpGynUB3aeHZAoWzGCx2XJmqhzOFl7zCa577QSy51oKPYWWzLeC8lNoeqEaLpjNFArcZCEQZCrUBsKxlCZC8hZCj4Wfw2fSp2aZBlUQ7AACAerP273AHBIFszPgzuWQZD` resulted in a `400 Bad Request` response:
{"error":{"message":"Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi (truncated...)
 in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[04-Aug-2018 13:01:07 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=EAAWZA5YNHROMBACZBbgEsZBEKADq1B9OhypiOAIpMokcnIKL8F3K0SYUenzTkVVLGPWLGQpGynUB3aeHZAoWzGCx2XJmqhzOFl7zCa577QSy51oKPYWWzLeC8lNoeqEaLpjNFArcZCEQZCrUBsKxlCZC8hZCj4Wfw2fSp2aZBlUQ7AACAerP273AHBIFszPgzuWQZD` resulted in a `400 Bad Request` response:
{"error":{"message":"Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi (truncated...)
 in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[04-Aug-2018 13:25:43 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=EAAWZA5YNHROMBACZBbgEsZBEKADq1B9OhypiOAIpMokcnIKL8F3K0SYUenzTkVVLGPWLGQpGynUB3aeHZAoWzGCx2XJmqhzOFl7zCa577QSy51oKPYWWzLeC8lNoeqEaLpjNFArcZCEQZCrUBsKxlCZC8hZCj4Wfw2fSp2aZBlUQ7AACAerP273AHBIFszPgzuWQZD` resulted in a `400 Bad Request` response:
{"error":{"message":"Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi (truncated...)
 in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[04-Aug-2018 13:25:48 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=EAAWZA5YNHROMBACZBbgEsZBEKADq1B9OhypiOAIpMokcnIKL8F3K0SYUenzTkVVLGPWLGQpGynUB3aeHZAoWzGCx2XJmqhzOFl7zCa577QSy51oKPYWWzLeC8lNoeqEaLpjNFArcZCEQZCrUBsKxlCZC8hZCj4Wfw2fSp2aZBlUQ7AACAerP273AHBIFszPgzuWQZD` resulted in a `400 Bad Request` response:
{"error":{"message":"Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi (truncated...)
 in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[04-Aug-2018 13:25:53 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/v2.6/me/messages?access_token=EAAWZA5YNHROMBACZBbgEsZBEKADq1B9OhypiOAIpMokcnIKL8F3K0SYUenzTkVVLGPWLGQpGynUB3aeHZAoWzGCx2XJmqhzOFl7zCa577QSy51oKPYWWzLeC8lNoeqEaLpjNFArcZCEQZCrUBsKxlCZC8hZCj4Wfw2fSp2aZBlUQ7AACAerP273AHBIFszPgzuWQZD` resulted in a `400 Bad Request` response:
{"error":{"message":"Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi (truncated...)
 in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp in /home/click4cl/test.click4click.net/facebook-messenger-send-api-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by RoySegall** [comment]
I think this is the problem: Unsupported post request. Object with ID 'me' does not exist, cannot be loaded due to missing permi...

I'll try set it up again on my localhost and update as I progress. In the mean while, try to look up the error at google.
